services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: collabo
      POSTGRES_USER: collabo_user
      POSTGRES_PASSWORD: collabo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env  # <-- This explicitly tells Docker to read the .env file
    depends_on:
      - db
    restart: always

volumes:
  postgres_data: