spring.datasource.url=jdbc:postgresql://${SPRING_DATASOURCE_URL:localhost:5432/collabo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:collabo_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:collabo_password}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true

# Resend SMTP Configuration
spring.mail.host=smtp.resend.com
spring.mail.port=587
spring.mail.username=resend
spring.mail.password=re_MRrHh2Hc_2cQR91fLV3T115Xa1sPoUWWA
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
